# SEO Meta Tags for RivalSearchMCP Documentation

# Home Page
index.md:
  title: "RivalSearchMCP - Advanced Multi-Engine Search & Content Analysis MCP Server"
  description: "Powerful MCP server for web research, content discovery, trends analysis, and intelligent crawling. Connect to AI assistants for enhanced research capabilities."
  keywords: "MCP server, web research, content analysis, trends analysis, AI assistant, web scraping, data extraction"
  author: "RivalSearchMCP Team"
  og_title: "RivalSearchMCP - Advanced Research MCP Server"
  og_description: "Connect AI assistants to powerful web research and content analysis tools"
  og_type: "website"
  og_image: "https://damionrashford.github.io/RivalSearchMCP/assets/rival-search-logo.png"

# Getting Started
getting-started/installation.md:
  title: "Installation Guide - RivalSearchMCP"
  description: "Learn how to install and connect RivalSearchMCP to your AI assistant. Step-by-step setup for Cursor, Claude Desktop, and VS Code."
  keywords: "MCP installation, AI assistant setup, Cursor MCP, Claude MCP, VS Code MCP"

getting-started/quick-start.md:
  title: "Quick Start Guide - RivalSearchMCP"
  description: "Get up and running with RivalSearchMCP in minutes. Quick setup guide for immediate use with AI assistants."
  keywords: "MCP quick start, fast setup, AI research tools, web search MCP"

# User Guide
user-guide/web-search.md:
  title: "Web Search Guide - RivalSearchMCP"
  description: "Master web search capabilities with RivalSearchMCP. Multi-engine search, anti-detection, and intelligent result processing."
  keywords: "web search, multi-engine search, anti-detection, search results, MCP search tools"

user-guide/content-extraction.md:
  title: "Content Extraction Guide - RivalSearchMCP"
  description: "Extract and analyze web content with RivalSearchMCP. HTML parsing, text cleaning, and structured data extraction."
  keywords: "content extraction, web scraping, HTML parsing, data extraction, MCP tools"

user-guide/trends-analysis.md:
  title: "Trends Analysis Guide - RivalSearchMCP"
  description: "Analyze search trends and keyword performance with RivalSearchMCP. Regional insights, related queries, and trend comparisons."
  keywords: "trends analysis, keyword research, search trends, regional insights, MCP trends"

# Examples
examples/search-examples.md:
  title: "Search Examples - RivalSearchMCP"
  description: "Real-world examples of using RivalSearchMCP for web search and research. Practical prompts and use cases."
  keywords: "MCP examples, search examples, research examples, practical usage, MCP prompts"

examples/business-cases.md:
  title: "Business Use Cases - RivalSearchMCP"
  description: "Discover how businesses use RivalSearchMCP for market research, competitor analysis, and content strategy."
  keywords: "business use cases, market research, competitor analysis, content strategy, MCP business"
